<?php

namespace AppBundle\Repository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends \Doctrine\ORM\EntityRepository
{
	public function purgeNullQuestion()
	{
		$qb = $this->createQueryBuilder('a');
	    	$qb
	    		->delete()
				->where('a.question is null')
	    		->getQuery()
	    		->execute();
	    	;
	}

	public function find($id)
	{
		$qb = $this->createQueryBuilder('a');
	    $qb
			->where('a.id = :id')
			->setParameter(':id', $id)
			->leftJoin('a.question', 'q')
			->addSelect('q')
			->setMaxResults(2)
    	;

    	$query = $qb->getQuery();
    	$query->useQueryCache(true);
        $query->useResultCache(true);
        $query->setResultCacheLifetime(60); // One minute
        $query->setCacheable(true);
    	
    	return $query->getOneOrNullResult();
	}
}
