<?php

namespace AppBundle\Repository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
	public function resultVote($Question)
	{
		$qb = $this->createQueryBuilder('a');
	    $qb
			->select($qb->expr()->count('a'))
			->where('a.question = :Question')
			->andWhere('a.choice = true')
			->setParameter(':Question', $Question)
			->setMaxResults(1)
    	;

    	$yes = $qb->getQuery()
    		->getSingleScalarResult();
    	;


    	if ($yes >= 5)
    	{
    		return 'accepted';
    	}


    	$qb = $this->createQueryBuilder('a');
	    $qb
			->select($qb->expr()->count('a'))
			->where('a.question = :Question')
			->andWhere('a.choice = false')
			->setParameter(':Question', $Question)
			->setMaxResults(1)
    	;

    	$no = $qb->getQuery()
    		->getSingleScalarResult();
    	;

    	if ($no >= 5)
    	{
    		return 'refused';
    	}

    	return 'wait';


	}

}
